SimpleConfig.for :application do

  set :colours, %w[lightblue red green orange yellow pink blue violet]
  set :shapes, %w[box ellipse hexagon  pentagon polygon trapezium parallelogram house]
  
  set :countries, ['ANDORRA', 'UNITED ARAB EMIRATES', 'AFGHANISTAN', 'ANTIGUA AND BARBUDA', 'ANGUILLA', 'ALBANIA', 'ARMENIA',
    'NETHERLANDS ANTILLES', 'ANGOLA', 'ANTARCTICA', 'ARGENTINA', 'AMERICAN SAMOA',
    'AUSTRIA', 'AUSTRALIA', 'ARUBA', 'AZERBAIJAN', 'BOSNIA AND HERZEGOVINA', 'BARBADOS', 'BANGLADESH', 'BELGIUM', 'BURKINA FASO',
    'BULGARIA', 'BAHRAIN', 'BURUNDI', 'BENIN', 'BERMUDA', 'BRUNEI DARUSSALAM', 'BOLIVIA', 'BRAZIL', 'BAHAMAS', 'BHUTAN', 'BOUVET ISLAND',
    'BOTSWANA', 'BELARUS', 'BELIZE', 'CANADA', 'COCOS ISLANDS', 'CONGO', 'CENTRAL AFRICAN REPUBLIC', 'CONGO', 'SWITZERLAND', 'COOK ISLANDS',
    'CHILE', 'CAMEROON', 'CHINA', 'COLOMBIA', 'COSTA RICA', 'CUBA', 'CAPE VERDE', 'CHRISTMAS ISLAND', 'CYPRUS', 'CZECH REPUBLIC', 'GERMANY',
    'DJIBOUTI', 'DENMARK', 'DOMINICA', 'DOMINICAN REPUBLIC', 'ALGERIA', 'ECUADOR', 'ESTONIA', 'EGYPT', 'WESTERN SARARA', 'ERITREA', 'SPAIN',
    'ETHIOPIA', 'FINLAND', 'FIJI', 'MALVINAS', 'FAROE ISLANDS', 'FRANCE', 'GABON', 'UNITED KINGDOM', 'GRENADA', 'GEORGIA', 'FRENCH GUIANA',
    'GHANA', 'GIBRALTAR', 'GREENLAND', 'GAMBIA', 'GUINEA', 'GUADELOUPE', 'EQUATORIAL GUINEA', 'GREECE', 'SOUTH GEORGIA', 'GUATEMALA', 'GUAM',
    'GUINEA-BISSAU', 'GUYANA', 'HONG KONG', 'HONDURAS', 'CROATIA', 'HAITI', 'HUNGARY', 'INDONESIA', 'IRELAND', 'ISRAEL', 'INDIA',
    'IRAQ', 'IRAN', 'ICELAND', 'ITALY', 'JAMAICA', 'JORDAN', 'JAPAN', 'KENYA', 'KYRGYZSTAN', 'CAMBODIA', 'KIRIBATI',
    'COMOROS', 'SAINT KITTS AND NEVIS', 'SOUTH KOREA', 'NORTH KOREA', 'KUWAIT', 'CAYMAN ISLANDS', 'KAZAKHSTAN', 'LEBANON', 'SAINT LUCIA',
    'LIECHTENSTEIN', 'SRI LANKA', 'LIBERIA', 'LESOTHO', 'LITHUANIA', 'LUXEMBOURG', 'LATVIA', 'LIBYA', 'MOROCCO', 'MONACO', 'MOLDOVA', 'MADAGASCAR', 'MARSHALL ISLANDS',
    'MACEDONIA', 'MALI', 'MYANMAR', 'MONGOLIA', 'MACAU', 'MARTINIQUE', 'MAURITANIA', 'MONTSERRAT', 'MALTA', 'MAURITIUS', 'MALDIVES', 'MALAWI', 'MEXICO', 'MALAYSIA',
    'MOZAMBIQUE', 'NAMIBIA', 'NEW CALEDONIA', 'NIGER', 'NORFOLK ISLAND', 'NIGERIA', 'NICARAGUA', 'NETHERLANDS', 'NORWAY', 'NEPAL',
    'NIUE', 'NEW ZEALAND', 'OMAN', 'PANAMA', 'PERU', 'FRENCH POLYNESIA', 'PAPUA NEW GUINEA', 'PHILIPPINES', 'PAKISTAN', 'POLAND', 'PITCAIRN', 'PUERTO RICO', 'PORTUGAL',
    'PALAU', 'PARAGUAY', 'QATAR', 'ROMANIA', 'RWANDA', 'SAUDI ARABIA', 'SOLOMON ISLANDS', 'SEYCHELLES', 'SUDAN', 'SWEDEN',
    'SINGAPORE', 'SAINT HELENA', 'SLOVENIA', 'SLOVAKIA', 'SIERRA LEONE', 'SAN MARINO', 'SENEGAL', 'SOMALIA', 'SURINAME', 'EL SALVADOR',
    'SWAZILAND', 'CHAD', 'TOGO', 'THAILAND', 'TAJIKISTAN', 'TOKELAU', 'TURKMENISTAN', 'TUNISIA', 'TONGA', 'EAST TIMOR',
    'TURKEY', 'TRINIDAD AND TOBAGO', 'TUVALU', 'TAIWAN', 'TANZANIA', 'UKRAINE', 'UGANDA', 'UNITED STATES', 'URUGUAY', 'UZBEKISTAN',
    'VENEZUELA', 'VIRGIN ISLANDS', 'VIET NAM', 'VANUATU', 'WALLIS AND FUTUNA', 'SAMOA', 'YEMEN', 'MAYOTTE', 'YUGOSLAVIA', 'SOUTH AFRICA',
    'ZAMBIA', 'ZIMBABWE']

  load File.join(RAILS_ROOT, 'config', "settings", "#{RAILS_ENV}.rb"), :if_exists? => true
  load File.join(RAILS_ROOT, 'config', "settings", "local.rb"),        :if_exists? => true
  
end
